volumes:
  sw-api-credentials:
    name: sw-dev-api-credentials

networks:
  net-sw-dev-data:
    external: true

  net-sw-dev-valhalla:
    external: true

  net-sw-dev-pelias:
    external: true

  net-sw-dev-sw-internal:
    name: net-sw-dev-sw-internal
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.10.20.0/24

services:
  authservice:
    image: ghcr.io/swayrider/authservice:dev-latest
    #image: ghcr.io/swayrider/authservice:v0.1.1-chore-update-swlib
    container_name: sw-dev-authservice
    restart: unless-stopped
    environment:
      - "DB_HOST=postgres"
      - "DB_PORT=5432"
      - "DB_NAME=authdb"
      - "DB_USER=${POSTGRES_USER}"
      - "DB_PASSWORD=${POSTGRES_PASSWORD}"
      - "ADMIN_EMAIL=${AUTH_ADMIN_EMAIL}"
      - "ADMIN_PASSWORD=${AUTH_ADMIN_PASSWORD}"
      - "MAILER_ADDRESS=${AUTH_MAILER_ADDRESS}"
      - "REGISTRATION_MODE=${AUTH_REGISTRATION_MODE}"
      - "REGISTRATION_URL=${AUTH_REGISTRATION_URL}"
      - "COOKIE_NAMESPACE=${COOKIE_NAMESPACE}"
      - "MAILSERVICE_HOST=mailservice"
      - "MAILSERVICE_PORT=8081"
    ports:
      - "34001:8080"
      - "34101:8081"
      - "34201:8000"
    networks:
      - net-sw-dev-sw-internal
      - net-sw-dev-data

  mailservice:
    image: ghcr.io/swayrider/mailservice:dev-latest
    #image: ghcr.io/swayrider/mailservice:v0.1.1-chore-update-swlib
    container_name: sw-dev-mailservice
    restart: unless-stopped
    depends_on:
      authservice:
        condition: service_started
    environment:
      - "SMTP_HOST=${MAIL_SMTP_HOST}"
      - "SMTP_PORT=${MAIL_SMTP_PORT}"
      - "SMTP_USER=${MAIL_SMTP_USER}"
      - "SMTP_PASSWORD=${MAIL_SMTP_PASSWORD}"
      - "AUTHSERVICE_HOST=authservice"
      - "AUTHSERVICE_PORT=8081"
    ports:
      - "34002:8080"
      - "34102:8081"
    networks:
      - net-sw-dev-sw-internal
      - net-sw-dev-data

  regionservice:
    image: ghcr.io/swayrider/regionservice:dev-latest
    #image: ghcr.io/swayrider/regionservice:v0.1.1-feat-region-endpoint-auth
    container_name: sw-dev-regionservice
    restart: unless-stopped
    depends_on:
      authservice:
        condition: service_started
    environment:
      - "GEODATA_DIR=/data/geodata"
    volumes:
      - "${GEODATA_PATH}:/data/geodata:ro"
    ports:
      - "34003:8080"
      - "34103:8081"
    networks:
      - net-sw-dev-sw-internal
      - net-sw-dev-data

  routerservice:
    image: ghcr.io/swayrider/routerservice:dev-latest
    #image: ghcr.io/swayrider/routerservice:v0.1.1-feat-region-token-forwarding
    container_name: sw-dev-routerservice
    restart: unless-stopped
    depends_on:
      authservice:
        condition: service_started
    environment:
      - "PELIAS_PREFIX=pelias-"
      - "PELIAS_API_POSTFIX=-api"
      - "PELIAS_API_PORT=3100"
      - "VALHALLA_PREFIX=valhalla-"
      - "VALHALLA_PORT=8002"
      - "REGIONSERVICE_HOST=regionservice"
      - "REGIONSERVICE_PORT=8081"
      - "AUTHSERVICE_HOST=authservice"
      - "AUTHSERVICE_PORT=8081"
    ports:
      - "34004:8080"
      - "34104:8081"
    networks:
      - net-sw-dev-sw-internal
      - net-sw-dev-valhalla
      - net-sw-dev-pelias

  searchservice:
    image: ghcr.io/swayrider/searchservice:dev-latest
    #image: ghcr.io/swayrider/searchservice:v0.1.1-feat-search-endpoint-auth-docs
    container_name: sw-dev-searchservice
    restart: unless-stopped
    depends_on:
      authservice:
        condition: service_started
    environment:
      - "PELIAS_REGIONS=benelux=http://pelias-benelux-api:3100/v1,france=http://pelias-france-api:3100/v1,germany=http://pelias-germany-api:3100/v1"
      - "REGIONSERVICE_HOST=regionservice"
      - "REGIONSERVICE_PORT=8081"
      - "AUTHSERVICE_HOST=authservice"
      - "AUTHSERVICE_PORT=8081"
    ports:
      - "34007:8080"
      - "34107:8081"
    networks:
      - net-sw-dev-sw-internal
      - net-sw-dev-pelias

  swayrider-api-register:
    image: ghcr.io/swayrider/swctl:dev-latest
    #image: ghcr.io/swayrider/swctl:v0.1.2-feat-region-auth
    container_name: sw-dev-swayrider-api-register
    restart: no
    depends_on:
      authservice:
        condition: service_started
    environment:
      - "AUTH_HOST=authservice"
      - "AUTH_PORT=8081"
      - "AUTH_USER=${AUTH_ADMIN_EMAIL}"
      - "AUTH_PASSWORD=${AUTH_ADMIN_PASSWORD}"
      - "REQUIRED_SCOPES=region:query routing:execute search:execute tiles:serve"
      - "FORCE_REREGISTER=${FORCE_REREGISTER:-false}"
    volumes:
      - sw-api-credentials:/credentials
      - ./swayrider-api-register/init.sh:/scripts/init.sh:ro
    entrypoint: ["/bin/sh"]
    command: /scripts/init.sh
    networks:
      - net-sw-dev-sw-internal

  tilesservice:
    image: ghcr.io/swayrider/tilesservice:dev-latest
    #image: ghcr.io/swayrider/tilesservice:v0.1.1-feat-tile-endpoint-auth
    container_name: sw-dev-tilesservice
    restart: unless-stopped
    depends_on:
      authservice:
        condition: service_started
    environment:
      - "TILES_PATH=/data/tiles"
      - "COMPRESSION_ENABLED=${TILESSERVICE_COMPRESSION_ENABLED}"
      - "COMPRESSION_CACHE_SIZE=${TILESSERVICE_COMPRESSION_CACHE_SIZE}"
      - "DISK_CACHE_ENABLED=${TILESSERVICE_DISK_CACHE_ENABLED}"
      - "DISK_CACHE_PATH=/data/cache/tiles"
      - "DISK_CACHE_MAX_FILES=${TILESSERVICE_DISK_CACHE_MAX_FILES}"
      - "SERVICE_HOST=${TILESSERVICE_PUBLIC_HOST_NAME}"
      - "SERVICE_PORT=${TILESSERVICE_PUBLIC_PORT}"
      - "SERVICE_PREFIX=${TILESSERVICE_PUBLIC_PATH_PREFIX}"
      - "AUTHSERVICE_HOST=authservice"
      - "AUTHSERVICE_PORT=8081"
    volumes:
      - "${TILES_DATA_PATH}:/data/tiles:ro"
      - "${TILES_CACHE_PATH}:/data/cache"
    ports:
      - "34005:8080"
    networks:
      - net-sw-dev-sw-internal
