networks:
  net-sw-dev-data:
    external: true

  net-sw-dev-valhalla:
    name: net-sw-dev-valhalla
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24

  net-sw-dev-pelias:
    name: net-sw-dev-pelias
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.0/24

services:
  valhalla-baltics-russia:
    image: ghcr.io/nilsnolde/docker-valhalla/valhalla:latest
    container_name: sw-dev-valhalla-baltics-russia
    restart: unless-stopped
    environment:
      - "use_tiles_ignore_pbf=True"
      - "force_rebuild=False"
      - "server_threads=${VALHALLA_SERVER_THREADS}"
    ports:
      - "33001:8002"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - '${VALHALLA_DATA_PATH}/baltics-russia:/custom_files'
      - './valhalla/baltics-russia/valhalla.json:/custom_files/valhalla.json:ro'
    networks:
      - net-sw-dev-valhalla
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  valhalla-central-europe:
    image: ghcr.io/nilsnolde/docker-valhalla/valhalla:latest
    container_name: sw-dev-valhalla-central-europe
    restart: unless-stopped
    environment:
      - "use_tiles_ignore_pbf=True"
      - "force_rebuild=False"
      - "server_threads=${VALHALLA_SERVER_THREADS}"
    ports:
      - "33002:8002"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - '${VALHALLA_DATA_PATH}/central-europe:/custom_files'
      - './valhalla/central-europe/valhalla.json:/custom_files/valhalla.json:ro'
    networks:
      - net-sw-dev-valhalla
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  valhalla-iberian-peninsula:
    image: ghcr.io/nilsnolde/docker-valhalla/valhalla:latest
    container_name: sw-dev-valhalla-iberian-peninsula
    restart: unless-stopped
    environment:
      - "use_tiles_ignore_pbf=True"
      - "force_rebuild=False"
      - "server_threads=${VALHALLA_SERVER_THREADS}"
    ports:
      - "33003:8002"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - '${VALHALLA_DATA_PATH}/iberian-peninsula:/custom_files'
      - './valhalla/iberian-peninsula/valhalla.json:/custom_files/valhalla.json:ro'
    networks:
      - net-sw-dev-valhalla
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  valhalla-scandinavia:
    image: ghcr.io/nilsnolde/docker-valhalla/valhalla:latest
    container_name: sw-dev-valhalla-scandinavia
    restart: unless-stopped
    environment:
      - "use_tiles_ignore_pbf=True"
      - "force_rebuild=False"
      - "server_threads=${VALHALLA_SERVER_THREADS}"
    ports:
      - "33004:8002"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - '${VALHALLA_DATA_PATH}/scandinavia:/custom_files'
      - './valhalla/scandinavia/valhalla.json:/custom_files/valhalla.json:ro'
    networks:
      - net-sw-dev-valhalla
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  valhalla-south-eastern-europe:
    image: ghcr.io/nilsnolde/docker-valhalla/valhalla:latest
    container_name: sw-dev-valhalla-south-eastern-europe
    restart: unless-stopped
    environment:
      - "use_tiles_ignore_pbf=True"
      - "force_rebuild=False"
      - "server_threads=${VALHALLA_SERVER_THREADS}"
    ports:
      - "33005:8002"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - '${VALHALLA_DATA_PATH}/south-eastern-europe:/custom_files'
      - './valhalla/south-eastern-europe/valhalla.json:/custom_files/valhalla.json:ro'
    networks:
      - net-sw-dev-valhalla
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  valhalla-south-europe:
    image: ghcr.io/nilsnolde/docker-valhalla/valhalla:latest
    container_name: sw-dev-valhalla-south-europe
    restart: unless-stopped
    environment:
      - "use_tiles_ignore_pbf=True"
      - "force_rebuild=False"
      - "server_threads=${VALHALLA_SERVER_THREADS}"
    ports:
      - "33006:8002"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - '${VALHALLA_DATA_PATH}/south-europe:/custom_files'
      - './valhalla/south-europe/valhalla.json:/custom_files/valhalla.json:ro'
    networks:
      - net-sw-dev-valhalla
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  valhalla-uk-iceland:
    image: ghcr.io/nilsnolde/docker-valhalla/valhalla:latest
    container_name: sw-dev-valhalla-uk-iceland
    restart: unless-stopped
    environment:
      - "use_tiles_ignore_pbf=True"
      - "force_rebuild=False"
      - "server_threads=${VALHALLA_SERVER_THREADS}"
    ports:
      - "33007:8002"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - '${VALHALLA_DATA_PATH}/uk-iceland:/custom_files'
      - './valhalla/uk-iceland/valhalla.json:/custom_files/valhalla.json:ro'
    networks:
      - net-sw-dev-valhalla
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  valhalla-west-europe:
    image: ghcr.io/nilsnolde/docker-valhalla/valhalla:latest
    container_name: sw-dev-valhalla-west-europe
    restart: unless-stopped
    environment:
      - "use_tiles_ignore_pbf=True"
      - "force_rebuild=False"
      - "server_threads=${VALHALLA_SERVER_THREADS}"
    ports:
      - "33008:8002"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - '${VALHALLA_DATA_PATH}/west-europe:/custom_files'
      - './valhalla/iberian-peninsula/valhalla.json:/custom_files/valhalla.json:ro'
    networks:
      - net-sw-dev-valhalla
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  pelias-placeholder:
    image: pelias/placeholder:latest
    container_name: sw-dev-pelias-placeholder
    restart: unless-stopped
    environment:
      - "PLACEHOLDER_DATA=/data"
    ports:
      - "33100:3000"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/placeholder/data:/data"
    networks:
      - net-sw-dev-pelias

  pelias-libpostal:
    image: pelias/libpostal-service:latest
    container_name: sw-dev-pelias-libpostal
    restart: unless-stopped
    ports:
      - "33101:4400"
    networks:
      - net-sw-dev-pelias

  pelias-baltics-russia-pip:
    image: pelias/pip-service:latest
    container_name: sw-dev-pelias-baltics-russia-pip
    restart: unless-stopped
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33110:3102"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/baltics-russia/pip/whosonfirst:/data/whosonfirst"
      - "${PELIAS_DATA_PATH}/baltics-russia/pip/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias

  pelias-central-europe-pip:
    image: pelias/pip-service:latest
    container_name: sw-dev-pelias-central-europe-pip
    restart: unless-stopped
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33120:3102"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/central-europe/pip/whosonfirst:/data/whosonfirst"
      - "${PELIAS_DATA_PATH}/central-europe/pip/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias

  pelias-iberian-peninsula-pip:
    image: pelias/pip-service:latest
    container_name: sw-dev-pelias-iberian-peninsula-pip
    restart: unless-stopped
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33130:3102"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/iberian-peninsula/pip/whosonfirst:/data/whosonfirst"
      - "${PELIAS_DATA_PATH}/iberian-peninsula/pip/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias

  pelias-scandinavia-pip:
    image: pelias/pip-service:latest
    container_name: sw-dev-pelias-scandinavia-pip
    restart: unless-stopped
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33140:3102"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/scandinavia/pip/whosonfirst:/data/whosonfirst"
      - "${PELIAS_DATA_PATH}/scandinavia/pip/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias

  pelias-south-eastern-europe-pip:
    image: pelias/pip-service:latest
    container_name: sw-dev-pelias-south-eastern-europe-pip
    restart: unless-stopped
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33150:3102"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/south-eastern-europe/pip/whosonfirst:/data/whosonfirst"
      - "${PELIAS_DATA_PATH}/south-eastern-europe/pip/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias

  pelias-south-europe-pip:
    image: pelias/pip-service:latest
    container_name: sw-dev-pelias-south-europe-pip
    restart: unless-stopped
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33160:3102"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/south-europe/pip/whosonfirst:/data/whosonfirst"
      - "${PELIAS_DATA_PATH}/south-europe/pip/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias

  pelias-uk-iceland-pip:
    image: pelias/pip-service:latest
    container_name: sw-dev-pelias-uk-iceland-pip
    restart: unless-stopped
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33170:3102"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/uk-iceland/pip/whosonfirst:/data/whosonfirst"
      - "${PELIAS_DATA_PATH}/uk-iceland/pip/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias

  pelias-west-europe-pip:
    image: pelias/pip-service:latest
    container_name: sw-dev-pelias-west-europe-pip
    restart: unless-stopped
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33180:3102"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/west-europe/pip/whosonfirst:/data/whosonfirst"
      - "${PELIAS_DATA_PATH}/west-europe/pip/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias

  pelias-baltics-russia-api:
    image: pelias/api:latest
    container_name: sw-dev-pelias-baltics-russia-api
    restart: unless-stopped
    depends_on:
      - pelias-baltics-russia-pip
      - pelias-libpostal
      - pelias-placeholder
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33111:3100"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/baltics-russia/api/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias
      - net-sw-dev-data

  pelias-central-europe-api:
    image: pelias/api:latest
    container_name: sw-dev-pelias-central-europe-api
    restart: unless-stopped
    depends_on:
      - pelias-central-europe-pip
      - pelias-libpostal
      - pelias-placeholder
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33121:3100"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/central-europe/api/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias
      - net-sw-dev-data

  pelias-iberian-peninsula-api:
    image: pelias/api:latest
    container_name: sw-dev-pelias-iberian-peninsula-api
    restart: unless-stopped
    depends_on:
      - pelias-iberian-peninsula-pip
      - pelias-libpostal
      - pelias-placeholder
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33131:3100"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/iberian-peninsula/api/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias
      - net-sw-dev-data

  pelias-scandinavia-api:
    image: pelias/api:latest
    container_name: sw-dev-pelias-scandinavia-api
    restart: unless-stopped
    depends_on:
      - pelias-scandinavia-pip
      - pelias-libpostal
      - pelias-placeholder
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33141:3100"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/scandinavia/api/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias
      - net-sw-dev-data

  pelias-south-eastern-europe-api:
    image: pelias/api:latest
    container_name: sw-dev-pelias-south-eastern-europe-api
    restart: unless-stopped
    depends_on:
      - pelias-south-eastern-europe-pip
      - pelias-libpostal
      - pelias-placeholder
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33151:3100"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/south-eastern-europe/api/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias
      - net-sw-dev-data

  pelias-south-europe-api:
    image: pelias/api:latest
    container_name: sw-dev-pelias-south-europe-api
    restart: unless-stopped
    depends_on:
      - pelias-south-europe-pip
      - pelias-libpostal
      - pelias-placeholder
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33161:3100"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/south-europe/api/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias
      - net-sw-dev-data

  pelias-uk-iceland-api:
    image: pelias/api:latest
    container_name: sw-dev-pelias-uk-iceland-api
    restart: unless-stopped
    depends_on:
      - pelias-uk-iceland-pip
      - pelias-libpostal
      - pelias-placeholder
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33171:3100"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/uk-iceland/api/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias
      - net-sw-dev-data

  pelias-west-europe-api:
    image: pelias/api:latest
    container_name: sw-dev-pelias-west-europe-api
    restart: unless-stopped
    depends_on:
      - pelias-west-europe-pip
      - pelias-libpostal
      - pelias-placeholder
    environment:
      - "PELIAS_CONFIG=/etc/config/pelias.json"
    ports:
      - "33181:3100"
    volumes:
      - '${GEODATA_PATH}:/geodata'
      - "${PELIAS_DATA_PATH}/west-europe/api/config:/etc/config:ro"
    networks:
      - net-sw-dev-pelias
      - net-sw-dev-data
